spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flametalk_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: flame
    password: flame123!@#

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: flametalk-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
