server:
  port: 8083

spring:
  application:
    name: file
  profiles:
    active: default
  cloud:
    config:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flametalk_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: flame
    password: flame123!@#

eureka:
  instance:
    hostname: file
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloud:
  aws:
    credentials:
      accessKey: AKIAZ4JHLYUEGDRSTI7C
      secretKey: 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
    s3:
      bucket: flametalk-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
