server:
  port: 8086

spring:
  application:
    name: presence # 유레카에 등록할 서비스의 논리 이름
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

  redis:
    host: localhost
    port: ${REDIS_PORT}

eureka:
  instance:
    hostname: presence
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카에 서비스 등록
    fetch-registry: true      # 유레카 서비스 위치
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 레지스트리 사본을 로컬로 가져오기