server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: auth
          uri: lb://auth # http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/device/**
          filters:
            - AddRequestHeaderFilter
        - id: membership
          uri: lb://membership # http://localhost:8082
          predicates:
            - Path=/api/membership/**
          filters:
            - AddRequestHeaderFilter
        - id: file
          uri: lb://file # http://localhost:8083
          predicates:
            - Path=/api/file/**
          filters:
            - AddRequestHeaderFilter
        - id: chatroom
          uri: lb://chatroom # http://localhost:8084
          predicates:
            - Path=/api/chatroom/**
          filters:
            - AddRequestHeaderFilter

        - id: chat
          uri: lb:ws://chat # ws://localhost:8085
          predicates:
            - Path=/stomp/**
        - id: chat
          uri: lb:ws://chat
          predicates:
            - Path=/chat/**
          filters:
            - AddRequestHeaderFilter
        - id: chat
          uri: lb://chat
          predicates:
            - Path=/api/chat/**
          filters:
            - AddRequestHeaderFilter

        - id: presence
          uri: lb:ws://presence # ws://localhost:8086
          predicates:
            - Path=/presence/**

  jwt:
    secret: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'routes'